---
title: "HW 1"
author: "Evan Dragich"
date: "25 January 2022"
output: 
  pdf_document: 
    extra_dependencies: ["actuarialsymbol", "actuarialangle", "amsmath"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 1.5

### a

$$
\begin{aligned}
A(4) &= \frac{1000}{1 - 0.06 \times 4} \\
&= \frac{1000}{1 - 0.24} \\
&= \frac{1000}{0.76} \\
&= \$ 1315.79
\end{aligned}
$$

### b

$$
\begin{aligned}
A(4) &= 1000 \times (1 + 0.06 \times 4) \\
&= 1000 \times (1.24) \\
&= \$ 1240.00
\end{aligned}
$$

### c

$$
\begin{aligned}
A(4) &= 1000 \times (1 + 0.06) ^ 4 \\
&= 1000 \times (1.262) \\
&= \$ 1262.48
\end{aligned}
$$

### d

$$
\begin{aligned}
r^{(4)} &= 0.06 \\
i(t) &= (1 + \frac{r^{(m)}}{m})^ {m} - 1 \\
&= {(1 + \frac{0.06}{4})}^ {4} - 1 \\
&= {(1 + 0.015)}^ {4} - 1 \\
&= 0.0614 \\ \\ \\
A(4) &= 1000 \times (1 + 0.0614) ^ 4 \\
&= 1000 \times (1.269) \\
&= \$ 1268.99
\end{aligned}
$$

### e

$$
\begin{aligned}
d^{(12)} &= 0.06 \\
i(t) &= (1 - \frac{d^{(m)}}{m})^ {-m} - 1 \\
&= {(1 - \frac{0.06}{12})}^ {-12} - 1 \\
&= {(1 - 0.005)}^ {-12} - 1 \\
&= 0.0620 \\ \\ \\
A(4) &= 1000 \times (1 + 0.0620) ^ 4 \\
&= 1000 \times (1.272) \\
&= \$ 1272.01
\end{aligned}
$$

### f

$$
\begin{aligned}
A(4) &= 1000 \times e ^ {\delta t} \\
&= 1000 \times e ^ {0.06 \times 4} \\
&= 1000 \times e ^ {0.24} \\
&= 1000 \times (1.271) \\
&= \$ 1271.25
\end{aligned}
$$

## 1.9

### Present Value

$$
\begin{aligned}
A(0) &= \sum_{i = 1}^{5}{C_{t} \times (1 + i)^{-t}} \\
&= \sum_{i = 1}^{5}{C_{t} \times (1.02)^{-t}} \\
&= 950 \times (1.02)^{0} + 800 \times (1.02)^{-1} + 150 \times (1.02)^{-2} + 400 \times (1.02)^{-3} + 120 \times (1.02)^{-4} \\
&= 950 \times 1 + 800 \times 0.9804 + 150 \times 0.9612 + 400 \times 0.9423 + 120 \times 0.9239 \\
&= 950 + 784.314 + 144.175 + 376.9289 + 110.8615 \\
&= \$2366.28
\end{aligned}
$$

### A(5)

To calculate the value in 5 years, we could begin as above, and accumulate each cash flow individually to $t = 5$ rather thatn $t = 0$. However, it is equivalent to simply accumulate the sum as a whole.

$$
\begin{aligned}
A(5) &= A(0) \times 1.02^5 \\
&= \$2366.28 \times 1.10408 \\
&= \$2612.56
\end{aligned}
$$

### 1.36

To solve for the interest earned in the fifth year, we can subtract $A(5) - A(4)$

$$
\begin{aligned}
A(5) &= A(0) \times \int_{0}^{5} \frac{1}{10(1+t)^{3}}dt \\
A(4) &= A(0) \times \int_{0}^{4} \frac{1}{10(1+t)^{3}}dt \\
A(5) - A(4)&= A(0) \times \int_{0}^{5} \frac{1}{10(1+t)^{3}}dt - A(0) \times \int_{0}^{4} \frac{1}{10(1+t)^{3}}dt \\
&= A(0) \times (\int_{0}^{5} \frac{1}{10(1+t)^{3}}dt - \int_{0}^{4} \frac{1}{10(1+t)^{3}}dt) \\
&= A(0) \times (\int_{4}^{5} \frac{1}{10(1+t)^{3}}dt) \\
&= 100 \times \frac{1}{10} \times \int_{4}^{5} {(1+t)^{-3}}dt \\
&= 10 \times  \frac{-(1+t)^{-2}}{2}\rvert_{4}^{5} \\
&= 10 \times  (\frac{-(1+5)^{-2}}{2} - \frac{-(1+4)^{-2}}{2}) \\
&= 5 \times  ((1+4)^{-2}-(1+5)^{-2}) \\
&= 5 \times  (\frac{1}{25}-\frac{1}{36}) \\
&= 5 \times  (0.0122) \\
&= \$ 0.0611
\end{aligned}
$$

### 1.42

$$
\begin{aligned}
a(t) = e^{\int_{0}^{t}\delta(s)ds}
\end{aligned}
$$

To solve for $a_{x}(t) = a_{y}(t)$, we must equate:

$$
\begin{aligned}
e^{\int_{0}^{t}\delta_{x}(s)ds} &= e^{\int_{0}^{t}\delta_{y}(s)ds} \\
\int_{0}^{t}\delta_{x}(s)ds &= \int_{0}^{t}\delta_{y}(s)ds
\end{aligned}
$$

Observing the graph, $\delta_{x}(s) = 0.1t$ for $t \in [0, 10]$ and $\delta_{y}(s) = 0.025t$ for $t \in [0, 2)$ and $0.05$ or $t \in [2, 10]$.

Thus, integrating both functions to solve for the $t$ in which they are equal:

$$
\begin{aligned}
\Delta_{x}(t) &= \int_{0}^{t}\delta_{x}(s)ds \\
&= \int_{0}^{t}0.01(s)ds \\
&= 0.005t^2
\end{aligned}
$$

$$
\begin{aligned}
\Delta_{y}(t) &= \int_{0}^{t}\delta_{y}(s)ds \\
&= \int_{0}^{t}0.025(s)ds\text{ , 0}\leq\text{t} \leq 2 \\
&\hphantom{=}\int_{0}^{2}0.025(s)ds+ \int_{2}^{t}0.05ds\text{  , 2} \leq {t} \leq \text{10} \\
&= 0.0125t^{2}\text{ , 0}\leq\text{t} < 2  \\
&\hphantom{=}0.05+ 0.05t-0.1\text{  , 2} \leq {t} \leq \text{10}  \\
&= 0.0125t^{2}\text{ , 0}\leq\text{t} < 2  \\
&\hphantom{=}-0.05+ 0.05t\text{  , 2} \leq {t} \leq \text{10}  \\
&= 0.0125t^{2}\text{ , 0}\leq\text{t} < 2  \\
&\hphantom{=}0.05(t - 1) \text{  , 2} \leq {t} \leq \text{10}  \\
\end{aligned}
$$

Thus, to solve for points where $0 \leq t < 2$, we must equate 

$$
\begin{aligned}
0.005t^2 &= 0.0125t^2 \\
t &= 0
\end{aligned}
$$

To solve for points where $\text{2} \leq {t} \leq \text{10}$, we must equate 

$$
\begin{aligned}
0.005t^2 &= -0.05 + 0.05t \\
0.005t^2 -0.05t + 0.05 &= 0 \\
0.005(t^{2} - 10 + 10) &= 0 \\
t &=  5 \pm \sqrt{15}
\end{aligned}
$$

Given the constraint of $\text{2} \leq {t} \leq \text{10}$ for this equality, we find $t = 5 + \sqrt{15} = 8.873$. Thus, the two solutions are $t = \{0, 8.873\}$.

# 2.5

### a

$$
\begin{aligned}
AV(750\ax{\angl{8}{4\%}}) &= 750\sum_{k = 0}^{7}(1.04)^k \\
&= 750(9.21423) \\
&= \$ 6910.67
\end{aligned}
$$

### b

$$
\begin{aligned}
i_{effective} &= 1.04^{2} - 1 \\
&= 0.0816 \\
AV(750\ax{\angl{8}{8.16\%}}) &= 750\sum_{k = 0}^{3}(1.0816)^k \\
&= 750(4.51678) \\
&= \$ 3387.59
\end{aligned}
$$

### c

$$
\begin{aligned}
i_{effective} &= 1.04^{\frac{1}{2}} - 1 \\
&= 0.0198 \\
AV(750\ax{\angl{8}{1.98\%}}) &= 750\sum_{k = 0}^{3}(1.0198)^k \\
&= 750(8.57691) \\
&= \$ 6432.68
\end{aligned}
$$

# 2.47

### a

$Rate(18, -1, 11, 0, 0) = 5.791\%$

### b

$Rate(18, -1, 11, 0, 1) = 6.656\%$

### c

$Rate(18, -1, 0, 28, 0) = 4.949\%$

### d

$Rate(18, -1, 0, 28, 1) = 4.478\%$

# 2.53

$$
\begin{aligned}
\sx{\angl{2n}} &= \sx{\angl{n}}(1 + i)^{-1} + \sx{\angl{n}} \\
y &= x(1 + i)^{-1} + x \\
y &= x((1 + i)^{-1} + 1) \\ \\ \\
(1 + i)^{-1} + 1 &= \frac{y}{x} \\
(1 + i)^{-1} &= \frac{y}{x} - 1\ \ \\ \\
\sx{\angl{kn}} &= \sx{\angl{n}}(1 + i)^{-(k - 1)} + \sx{\angl{n}} \\
&= x(\frac{y}{x} - 1)^{k - 1} + x \\
&= x((\frac{y}{x} - 1)^{k - 1} + 1) \\ \\ \\
\end{aligned}
$$

Thus, for $k = 1$, $\sx{\angl{kn}} = x$, and for $k \geq 2$, $\sx{\angl{kn}} =x((\frac{y}{x} - 1)^{k - 1} + 1)$

## 3.4

### a

$$
\begin{aligned}
i_{1}^{F} &= i_{1}^{S} \\
&= 2.1\% \\ \\
i_{2}^{S} &= (1 + i_{1}^{S})(1 + i_{2}^{F}) - 1 \\
&= (1.021)(1.026) - 1 \\
&= ((1.021)(1.026))^{\frac{1}{2}} - 1 \\
&= 2.35\% \\ \\
i_{3}^{F} &= \frac{(1 + i_{3}^{S})^{3}}{(1 + i_{2}^{S})^{2}} - 1 \\
&= \frac{(1.031)^{3}}{(1.0235)^{2}} - 1 \\
&= \frac{1.0959}{1.0476} - 1 \\
&= 4.62\% \\ \\
i_{4}^{S} &= ((1 + i_{3}^{S})^{3}(1 + i_{4}^{F}))^\frac{1}{4} - 1 \\
&= ((1.031)^{3}(1.036))^\frac{1}{4} - 1 \\
&= 3.22\%
\end{aligned}
$$

### b

$$
\begin{aligned}
\ax**{\angl{4}} &= \sum_{k = 0}^{3}(1 + i_{k}^{S})^{-k} \\
&= 1 + (1 + i_{1}^{S})^{-1} + (1 + i_{2}^{S})^{-2} + (1 + i_{3}^{S})^{-3} \\
&= 1 + (1.021)^{-1} + (1.0235)^{-2} + (1.031)^{-3} \\
&= 3.847
\end{aligned}
$$

To calculate $\sx**{\angl{4}}$, we could accumulate each cash flow individually, or accumulate the sum as a whole as such:

$$
\begin{aligned}
\sx**{\angl{4}} &= \ax**{\angl{4}}(1 + i_{1}^{S})^{3} \\
&= 3.847(1.031)^{3} \\
&= 4.215
\end{aligned}
$$

## 3.8

### a

$$
\begin{aligned}
100\ax{\angl{4}} &= 100\sum_{k = 1}^{4}(1 + i_{k}^{S})^{-k} \\
&=  100((1.06)^{-1} + (1.07)^{-2} + (1.0775)^{-3} + (1.0825)^{-4})
\\
&= 100(3.344469) \\
&= \$334.47
\end{aligned}
$$

### b

$Rate(4, -100, 334.447, 0, 0) = 7.565\%$

## 3.18

### a

$$
\begin{aligned}
R_{S} &= \frac{\sum_{t = 1}^{n}m_{t}i_{t}^{F}(1+i_{t}^{S})^{-t}}{\sum_{t = 1}^{n}m_{t}(1+i_{t}^{S})^{-t}} \\
&= \frac{\sum_{t = 1}^{n}i_{t}^{F}(1+i_{t}^{S})^{-t}}{\sum_{t = 1}^{n}(1+i_{t}^{S})^{-t}} \\
&= \frac{i_{1}^{F}(1+i_{1}^{S})^{-1} + i_{2}^{F}(1+i_{2}^{S})^{-2} + i_{3}^{F}(1+i_{3}^{S})^{-3} + i_{4}^{F}(1+i_{4}^{S})^{-4} + i_{5}^{F}(1+i_{5}^{S})^{-5}}{(1+i_{1}^{S})^{-1} + (1+i_{2}^{S})^{-2} + (1+i_{3}^{S})^{-3} + (1+i_{4}^{S})^{-4} + (1+i_{5}^{S})^{-5}} \\
&= \frac{0.0071(1.0071)^{-1} + 0.0079(1.0143)^{-2} + 0.0042(1.0205)^{-3} + 0.0031(1.0294)^{-4} + 0.0035(1.0355)^{-5}}{(1.0071)^{-1} + (1.0143)^{-2} + (1.0205)^{-3} + (1.0294)^{-4} + (1.0355)^{-5}} \\
&= 0.0052587 \\
&= 0.53\%
\end{aligned}
$$

### b

$$
\begin{aligned}
R_{S} &= \frac{\sum_{t = 1}^{n}m_{t}i_{t}^{F}(1+i_{t}^{S})^{-t}}{\sum_{t = 1}^{n}m_{t}(1+i_{t}^{S})^{-t}} \\
&= \frac{m_{1}i_{1}^{F}(1+i_{1}^{S})^{-1} + m_{2}i_{2}^{F}(1+i_{2}^{S})^{-2} + m_{3}i_{3}^{F}(1+i_{3}^{S})^{-3} + m_{4}i_{4}^{F}(1+i_{4}^{S})^{-4} + m_{5}i_{5}^{F}(1+i_{5}^{S})^{-5}}{m_{1}(1+i_{1}^{S})^{-1} + m_{2}(1+i_{2}^{S})^{-2} + m_{3}(1+i_{3}^{S})^{-3} + m_{4}(1+i_{4}^{S})^{-4} + m_{5}(1+i_{5}^{S})^{-5}} \\
&= \frac{1(0.0071)(1.0071)^{-1} + 3(0.0079)(1.0143)^{-2} + 5(0.0042)(1.0205)^{-3} + 7(0.0031)(1.0294)^{-4} + 9(0.0035)(1.0355)^{-5}}{1(1.0071)^{-1} + 3(1.0143)^{-2} + 5(1.0205)^{-3} + 7(1.0294)^{-4} + 9(1.0355)^{-5}} \\
&= 0.0042678 \\
&= 0.43\%
\end{aligned}
$$

### c

$$
\begin{aligned}
R_{S} &= \frac{\sum_{t = 1}^{n}m_{t}i_{t}^{F}(1+i_{t}^{S})^{-t}}{\sum_{t = 1}^{n}m_{t}(1+i_{t}^{S})^{-t}} \\
&= \frac{m_{1}i_{1}^{F}(1+i_{1}^{S})^{-1} + m_{2}i_{2}^{F}(1+i_{2}^{S})^{-2} + m_{3}i_{3}^{F}(1+i_{3}^{S})^{-3} + m_{4}i_{4}^{F}(1+i_{4}^{S})^{-4} + m_{5}i_{5}^{F}(1+i_{5}^{S})^{-5}}{m_{1}(1+i_{1}^{S})^{-1} + m_{2}(1+i_{2}^{S})^{-2} + m_{3}(1+i_{3}^{S})^{-3} + m_{4}(1+i_{4}^{S})^{-4} + m_{5}(1+i_{5}^{S})^{-5}} \\
&= \frac{5(0.0071)(1.0071)^{-1} + 4(0.0079)(1.0143)^{-2} + 3(0.0042)(1.0205)^{-3} + 2(0.0031)(1.0294)^{-4} + 1(0.0035)(1.0355)^{-5}}{5(1.0071)^{-1} + 4(1.0143)^{-2} + 3(1.0205)^{-3} + 2(1.0294)^{-4} + 1(1.0355)^{-5}} \\
&= 0.0060351 \\
&= 0.60\%
\end{aligned}
$$

### d

With a level notional contract, the annual fixed rate payment is 
$m_{t}R_{S}$, or $0.00525866 (1000000) = \$5258.66$

### e

$$
\begin{aligned}
MV_{3} &= \sum_{k = 3}^{5}m_{k}(R_{S} - i_{k}^{F}) \\
&= m_{k}\sum_{k = 3}^{5}(R_{S} - i_{k}^{F}) \\
&= 1000000\sum_{k = 3}^{5}(R_{S} - i_{k}^{F}) \\
&= 1000000((0.00525866 - 0.0042) + (0.00525866 - 0.0031) + (0.00525866 - 0.0035)) \\
&= 1000000(0.00497598) \\
&= \$4975.98
\end{aligned}
$$

### f

$$
\begin{aligned}
R_{S} &= \frac{\sum_{t = t^{*} + 1}^{n}m_{t}i_{t}^{F}(1+i_{t}^{S})^{-t}}{\sum_{t^{*} + 1}^{n}m_{t}(1+i_{t}^{S})^{-t}} \\
&= \frac{\sum_{t = 2}^{n}i_{t}^{F}(1+i_{t}^{S})^{-t}}{\sum_{t = 2}^{n}(1+i_{t}^{S})^{-t}} \\
&= \frac{i_{2}^{F}(1+i_{2}^{S})^{-2} + i_{3}^{F}(1+i_{3}^{S})^{-3} + i_{4}^{F}(1+i_{4}^{S})^{-4} + i_{5}^{F}(1+i_{5}^{S})^{-5}}{(1+i_{2}^{S})^{-2} + (1+i_{3}^{S})^{-3} + (1+i_{4}^{S})^{-4} + (1+i_{5}^{S})^{-5}} \\
&= \frac{0.0079(1.0143)^{-2} + 0.0042(1.0205)^{-3} + 0.0031(1.0294)^{-4} + 0.0035(1.0355)^{-5}}{(1.0143)^{-2} + (1.0205)^{-3} + (1.0294)^{-4} + (1.0355)^{-5}} \\
&= 0.0047568 \\
&= 0.48\%
\end{aligned}
$$