---
title: "Homework 5"
author: "Evan Dragich"
date: 1 April 2022
format: 
  pdf:
    header-includes:
      \usepackage{actuarialsymbol}
---

## 6.5

Consider a fully discrete 10-year term insurance issued to a select life aged 50, with sum insured $100000. Assume that mortality follows the Standard Select Life Table, and assume an interest rate of 5% per year.
(a) Write down an expression for the net loss at issue random variable. (b) Calculate the net annual premium.

$$
\begin{aligned}
L_{0}^{n} = 100000 (1.05)^{\text{min}(K_{[50]} + 1, 10)} - P
\end{aligned}
$$


## 6.11
For a whole life insurance issued to (55), you are given:
• initial annual premiums are level for 10 years; thereafter annual premiums equal one-half of initial annual premiums,
• the death benefit is $100 000 during the first 10 years of the contract, is $50 000 thereafter, and is payable at the end of the year of death, and
• expenses are 25% of the first year’s premium plus 3% of all subsequent premiums.
Calculate the initial annual gross premium, assuming that mortality follows the Standard Select Life Table, and that the interest rate is 5% per year.



## 7.1
For a whole life insurance issued to (40), you are given:
(i) The death benefit, which is payable at the end of the year of death, is $50 000 in the first 20 years, and $100 000 thereafter.
(ii) Level annual premiums are payable for 20 years or until earlier death.
(iii) The mortality basis for policy values is the Standard Ultimate Survival
Model.
(iv) The interest basis for policy values is 5% per year.
Calculate the net premium policy value, 10V.



## 7.2
A fully discrete whole life insurance with sum insured $10 000 is issued to a select life aged x. The net premium is $134. You are given that q[x] = 0.00106 and i = 0.045. Calculate 1Vn.



